// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgsibFdccqBfUFeEa0XJS9qq-WX19lqaE',
    appId: '1:865522229832:web:ec90b026f35b7d5acaee7d',
    messagingSenderId: '865522229832',
    projectId: 'muse-demo-1d634',
    authDomain: 'muse-demo-1d634.firebaseapp.com',
    storageBucket: 'muse-demo-1d634.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ6H8OODNb_EVnFh44PbwxDPuyy3v7lr0',
    appId: '1:865522229832:android:125c312ecca22988caee7d',
    messagingSenderId: '865522229832',
    projectId: 'muse-demo-1d634',
    storageBucket: 'muse-demo-1d634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOIbwW3E2YnZoMWeu5Owkmkxy9YK3RMw',
    appId: '1:865522229832:ios:54f51da1508ad2bccaee7d',
    messagingSenderId: '865522229832',
    projectId: 'muse-demo-1d634',
    storageBucket: 'muse-demo-1d634.appspot.com',
    iosClientId:
        '865522229832-75mk06ml52bq4ts2973rk6vs4qbai7uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOIbwW3E2YnZoMWeu5Owkmkxy9YK3RMw',
    appId: '1:865522229832:ios:89aa67a4328edbdccaee7d',
    messagingSenderId: '865522229832',
    projectId: 'muse-demo-1d634',
    storageBucket: 'muse-demo-1d634.appspot.com',
    iosClientId:
        '865522229832-a2qelh2dv80m0nfv4527mvdtlse7762n.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveyApp.RunnerTests',
  );
}
